### ISSUE TITLE
should be points not point

### ISSUE THREAD

**Issue by chekolasnergee** [eleven-lab/laravel-geo#1]
typo on readme.md

`protected $geometries = [
   ....
    "points"= ["capital"]`

**Comment by desh901** [comment]
Personally i do not agree, the associative array key indicates that **type** Point should be addressed to the  attributes included in the values array. We are not specifying an array of Point, but we are just saying "Consider the following attributes of type Point" it sounds wrong to me call that key "points". But i'm open to suggestions anyway, just explain your point if you think that i'm wrong :)

**Comment by desh901** [comment]
Thanks, we will fix it ASAP!
