### ISSUE TITLE
dropColumn not working on rollback

### ISSUE THREAD

**Issue by chuckienorton** [eleven-lab/laravel-geo#2]
I'm getting an error when running "php artisan migrate:rollback" Here is my code:

`Schema::table("mytable", function(Blueprint $table) {
            $table->multipolygon("radar_map")->after("radar_miles")->nullable()->comment("Overrides radar_radius_miles with a multipolygon."); 
        });`

`public function down()
    {
        Schema::table("mytable", function(Blueprint $table) {
            $table->dropColumn("radar_map");
        });
    }`

and the error...
`[Doctrine\DBAL\DBALException]
  Unknown database type multipolygon requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.`

I also tried a DB::RAW statement and got the same response. 

` DB::raw('ALTER TABLE mytable DROP radar_map;');
`

Any ideas how to do this would be appreciated!

**Comment by desh901** [comment]
@chuckienorton I suspect that could be a problem with your MySQL version and `doctrine/dbal` package. Could you try to drop another column (not a geometry) to see if the problem still occurs?

**Comment by chuckienorton** [comment]
Thanks for the quick reply.

I'm using MySQL 5.7 and yes all the other fields are working.

It's Laravel 5.4 so I'm assuming doctrine/dbal isn't a problem but not sure.

Ok, if this is a one off bug for me them I will possibly store the data as text and override the attribute in the model to serve it as a multipolygon.

Thanks guys!

**Comment by desh901** [comment]
We will conduct some tests to see if the bug lies in our implementation or it is somehow related to `doctrine/dbal` or Laravel 5.4 or a particular DB version!

You're welcome :)

**Comment by desh901** [comment]
As we are using this package with Laravel 5.4 without any kind of problem i'm going to close this. If further problems occurs i will re-open this issue.
