### ISSUE TITLE
multipolygon attribute showing up with wrong characters

### ISSUE THREAD

**Issue by chuckienorton** [eleven-lab/laravel-geo#3]
I'm having trouble getting a multipolygon field to show actual text from my database. Here is what I am doing. 

table column "radar_map" has the following data: 

`MULTIPOLYGON(((-84.0330505 38.4686433,-83.71444700000001 38.2424946,-83.6334229 38.177751,-83.5606384 38.231708,-83.5345459 38.2435731,-83.5153198 38.2575931,-83.4933472 38.2683758,-83.5057068 38.285625,-83.46176149999999 38.3712706,-83.58055109999999 38.4089441,-83.62106319999999 38.5363501,-83.8929749 38.463267,-83.95202639999999 38.5213097,-84.0330505 38.4686433),(-84.2266846 38.8193811,-84.2129517 38.6093591,-84.21157839999999 38.5599788,-84.1333008 38.5513874,-84.1140747 38.5878935,-84.02618409999999 38.5793055,-83.8799286 38.7610441,-83.964386 38.785134,-84.03717039999999 38.7680042,-84.1209412 38.7819225,-84.20471190000001 38.7979786,-84.2266846 38.8193811),(-84.1333008 38.5513874,-84.1964722 38.5449433,-84.181366 38.4869197,-84.118818 38.4153888,-84.0509034 38.3868806,-83.9836121 38.4288493,-84.0330505 38.4686433,-83.95202639999999 38.5213097,-84.02618409999999 38.5793055,-84.1140747 38.5878935,-84.1333008 38.5513874),(-83.8799286 38.7610441,-84.02618409999999 38.5793055,-83.9588928 38.5304417,-83.8929749 38.463267,-83.62106319999999 38.5363501,-83.6375427 38.6458357,-83.66912840000001 38.6233082,-83.73229980000001 38.6447631,-83.76800540000001 38.6511983,-83.7927246 38.7048027,-83.84216309999999 38.7187333,-83.8572693 38.7562251,-83.8799286 38.7610441),(-83.6375427 38.6458357,-83.6203766 38.5223841,-83.58055109999999 38.4089441,-83.46176149999999 38.3712706,-83.4157562 38.3960297,-83.31962590000001 38.2904755,-83.25027470000001 38.3529649,-83.20358280000001 38.489607,-83.0415344 38.6340365,-83.0140686 38.7267689,-83.0332947 38.7176618,-83.05183409999999 38.6930132,-83.1088257 38.66782,-83.141098 38.6190164,-83.2104492 38.6125783,-83.2475281 38.6227717,-83.2901001 38.5916505,-83.31825259999999 38.600237,-83.3278656 38.616334,-83.3333588 38.6388636,-83.38897710000001 38.6592415,-83.46794130000001 38.6672839,-83.5249329 38.7005158,-83.57574459999999 38.6828298,-83.6238098 38.6758613,-83.6375427 38.6458357)))`

Here is my model...

`    
    namespace App;
    
    //use Illuminate\Database\Eloquent\Model;
    use ElevenLab\GeoLaravel\Eloquent\Model as GeoModel;
    
    
    class My_model extends GeoModel
    {
    
        protected $geometries = [ // docs at https://github.com/eleven-lab/laravel-geo
            "multipolygons" => ['radar_map']
        ];
`

here is my dump: 

`dd($myModel->radar_map);`

and here is what i get: 

`
b"""
\x00\x00\x00\x00\x01\x06\x00\x00\x00\x01\x00\x00\x00\x01\x03\x00\x00\x00\x05\x00\x00\x00\x0E\x00\x00\x00t'Ï\x7F\x1D\x02U└¿~´Ç³;C@l¯Þ\x7F╣ÝT└r:$\x10\n
\x1FC@f\x024\x00èÞT└hÛuï└\x16C@o8Ô\x7FßÒT└\\x1Còø¿\x1DC@\x7F¡\x01\x006ÔT└╣WAg-\x1FC@═■Õ ·ÓT└o\x16è¤° C@»d"\x00ô▀T└Ï\x04b#Z"C@YÎ\rÇ]ÓT└├§(\Å$C@RC\eÇì¦T└░{å╦à/C@\t\n
═┐'ÕT└2▓┐GX4C@±/¦\x7F┐þT└iZ¢\x1EºDC@çÚ1Ç&¨T└t(CUL;C@n;#\x00¯³T└6K©F║BC@t'Ï\x7F\x1D\x02U└¿~´Ç³;C@\f\x00\x00\x00pÓ\x1F\x00é\x0EU└‗║┘zßhC@+╚*\x00í\rU└Å\x02ƒz MC@Å"!Çè\rU└\x07:ñb¡GC@÷!\x14\x00ê\x08U└ù6┴▄ôFC@Ds° L\x07U└¸\x03\x1E\x18@KC@6K\x13\x00¡\x01U└Kr└«&JC@*¶\v└P°T└)(áõiaC@\x19«\x0EÇ©²T└$}ZE\x7FdC@E\x18§ `\x02U└g\x18-÷MbC@L»(Ç¢\x07U└Î└V\t\x16dC@êµ­ \x19\rU└5¶¬)$fC@pÓ\x1F\x00é\x0EU└‗║┘zßhC@\v\x00\x00\x00÷!\x14\x00ê\x08U└ù6┴▄ôFC@»d"\x00ô\fU└PÍ╣│└EC@╬ª#Çø\vU└Üú}bS>C@F\vðÂÜ\x07U└÷Å¤u+5C@UÉU\x00B\x03U└z:▓Mà1C@╦\*Ç¾■T└═4½êõ6C@t'Ï\x7F\x1D\x02U└¿~´Ç³;C@n;#\x00¯³T└6K©F║BC@6K\x13\x00¡\x01U└Kr└«&JC@Ds° L\x07U└¸\x03\x1E\x18@KC@÷!\x14\x00ê\x08U└ù6┴▄ôFC@\r\x00\x00\x00*¶\v└P°T└)(áõiaC@6K\x13\x00¡\x01U└Kr└«&JC@¼\x17Þ\x7F^²T└ó¸|âÕCC@çÚ1Ç&¨T└t(CUL;C@±/¦\x7F┐þT└iZ¢\x1EºDC@môÕ\x7F═ÞT└m\và¥¬RC@╩┤ý ÊÛT└\x10*'É╚OC@â¸· ¦¯T└s\x15µÿçRC@▒\t\x1F\x00'±T└¹┌DwZSC@\x05´§ ╗‗T└÷Pæ¨6ZC@x\x19\x0F\x00µ§T└Þ\x05Ús [C@YÎ\rÇ¦÷T└\tuý¹╦`C@*¶\v└P°T└)(áõiaC@\x1A\x00\x00\x00môÕ\x7F═ÞT└m\và¥¬RC@\t\r\x0E@┤þT└ª╣p{¦BC@\t\n
═┐'ÕT└2▓┐GX4C@RC\eÇì¦T└░{å╦à/C@■åõ┐ø┌T└R▀Þ\x19▒2C@\x18¦0└tÈT└\x06e\x1AM.%C@\n
ß,Ç\x04ðT└f\x11/¶--C@═\x01'Ç\x07═T└Cr2q½>C@-jµ\x7F¿┬T└3³º\e(QC@ó9³\x7Fµ└T└²ƒh├\x06]C@TÞ\x17Ç!┬T└TKäW▄[C@S\x14¨?Q├T└!┘\x12¿┤XC@ÀØ\x11\x00¸ãT└»╬1 {UC@³ßþ┐\x07╔T└\x05ÏýÝ;OC@\n
ÌÙ w═T└í^:¸hNC@Ëò\x19ÇÎ¤T└Û/¬¹ÂOC@?ä\x02\x00æÊT└¥\x14\x1E4╗KC@|7'@^ÈT└▒lµÉÈLC@­^ ┐¹ÈT└┘┤R\x08õNC@]§%└UıT└kMNHãQC@&┘4\x00ÕÏT└?Uà\x06bTC@¿³\x10└‗¦T└▄Ê\x0FÅiUC@\vå)ÇÿßT└g¬qÇ¬YC@O÷Ó ÏõT└¹¦à¸fWC@({­\x7FýþT└þ\x10éƒéVC@môÕ\x7F═ÞT└m\và¥¬RC@
"""`

I've even tried various ways to override the attribute in the model but no luck. 

Any help would be super appreciated!

**Comment by desh901** [comment]
Seems like the package cannot decode the raw data from the DB. Let's wait @lorenzogiust to check if that is a bug or if it is somehow an error on the procedure of getting the attribute

**Comment by chuckienorton** [comment]
Ok thanks!

**Comment by lorenzogiust** [comment]
Hi @chuckienorton, you should try to do $myModel->radar_map->toWKT(), let me know if it works!

**Comment by chuckienorton** [comment]
Ahh perfect. Works great thanks!!

**Comment by chuckienorton** [comment]
Actually - it wasn't working perviously and I'm pretty sure a composer dump-autoload did the trick. Now the above $myModel->radar_map is correctly showing your class. 

Thanks again!
